### ISSUE TITLE
Create new conda/pip package for PropertyGraph

### ISSUE THREAD

**Issue by rlratzel** [rapidsai/cugraph-pg#11]
Who: end users, cugraph developers
What: Create a new package (cugraph and pip) for users with minimal dependencies needed only for core PG functionality
Why: The new PG implementation will likely have new dependencies not essential to other cugraph use cases, so a separate package benefits users by keeping dependencies for non-PG use cases to a minimum.

Questions: 
* PG won't (likely) depend on cugraph, but should cugraph depend on PG, perhaps if we want `cugraph.Graph` to have support for properties like NetworkX Graph? 
* If PG has a method to extract a `cugraph.Graph` subgraph, should it have a hard dependency on cugraph?  If so, does that remove a major advantage of having PG and cugraph in separate packages (ie. not requiring PG to have all cugraph deps)?

```[tasklist]
### Tasks
- [ ] Pick a name (probably one that matches dir name in source tree)
- [ ] Update CI scripts to build new PG package and run newly-located tests
- [ ] Add conda recipe, setup.py, etc. for new PG packages
- [ ] Add/update docs for new PG package
- [ ] Add/update notebook(s) for new PG package
```
